### ISSUE TITLE
Add ability to ignore warnings

### ISSUE THREAD

**Issue by zepatrik** [kevgo/text-runner#1401]
In some cases it might be desirable to manually approve a false positive. Especially when using a template like https://github.com/ory/meta/blob/master/templates/repository/common/CONTRIBUTING.md
As far as I could tell there is currently no way to ignore errors.
My suggestion would be a comment like

```md
<!-- text-run ignore linkTarget -->
Check out [ORY $PROJECT Discussions]($DISCUSSIONS). This is a great place for
...
```

that allows to disable checks by rule name (just like `// @ts-ignore ...` or others).

**Comment by kevgo** [comment]
Great idea Patrick!

**Comment by kevgo** [comment]
@zepatrik What do you think about this idea: a new configuration option for Text-Runner that allows to ignore all links that are made from template variables. In your case, it could look like this:

```yml
ignore-links:
  - "\\(\\$.*\\)"
```

This RegEx tells Text-Runner: "don't check Links whose URL starts with a `$`. 

Advantages:

- ignores all links that are made using template variables in one swoop
- comments like `<!-- text-run ignore linkTarget -->` don't pollute the output of the template
- when you verify the output of the template with Text-Runner, it would verify the link (since the rendered document doesn't contain the ignore-comment)

**Comment by zepatrik** [comment]
Nice, that works perfectly for my use case. I assume there are some cases where you still want to ignore false positives, but the advantages you mentioned are a good point to not ignore it generally.
